import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Icons, iconSize } from '../../components/icons/index.jsx';
import { CopilotPreview, CreativeLineagePreview, DeveloperFlow, DiffPreview } from '../../components/marketing/ProductPreviews.jsx';

const stories = [
  ['Creative Versioning', 'Capture the meaningful change, not merely another exported file.', 'A version carries its author, action, parents, and context.', Icons.History, 'lineage'],
  ['Creative Lineage', 'Follow ideas as they branch, converge, and become a decision.', 'A real DAG makes creative continuity visible.', Icons.GitBranch, 'lineage'],
  ['Semantic Diff', 'Understand how a direction changed, with declared and observed evidence.', 'Comparison remains grounded in actual work.', Icons.FileDiff, 'diff'],
  ['Creative Memory', 'Save the interpretation that helps the next decision make sense.', 'Memory complements lineage without rewriting history.', Icons.Library, 'copilot'],
  ['Canopy Copilot', 'Ask questions against work and receive grounded citations.', 'AI explains; Core remains authoritative.', Icons.Bot, 'copilot']
];

export function HomePage() {
  return <PageMeta title="Canopy | Creative work, with history" description="Canopy preserves creative versions, lineage, decisions, and AI-assisted understanding.">
    <section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-20 lg:grid-cols-[0.9fr_1.1fr] lg:gap-10 lg:px-8 lg:pt-28">
      <div className="self-center"><Eyebrow icon={Icons.Sparkles}>Creative evolution platform</Eyebrow><h1 className="mt-6 max-w-3xl text-5xl font-semibold leading-[1.02] text-white sm:text-6xl lg:text-7xl">Your creative work has a history.<span className="text-canopy-green"> Keep it understandable.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-canopy-secondary">Canopy records versions, lineage, creative decisions, and AI context so the next move begins with the story behind the work.</p><div className="mt-9 flex flex-wrap gap-3"><PrimaryLink to="/signup">Get started <Icons.ArrowRight className={iconSize.ui} /></PrimaryLink><SecondaryLink to="/how-it-works">Explore Canopy</SecondaryLink></div></div>
      <div className="self-center"><CreativeLineagePreview /></div>
    </section>
    <ProblemSection />
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><SectionHeading eyebrow="The core product" title="The work is more useful when its history survives." body="Canopy connects files, actions, decisions, and AI context that usually disappear between creative tools." /><div className="mt-14 space-y-16">{stories.map((story, i) => <FeatureStory key={story[0]} story={story} flip={i % 2} />)}</div></section>
    <section className="border-y border-canopy-border bg-canopy-surface/50"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 lg:grid-cols-2 lg:px-8"><div><Eyebrow icon={Icons.Sparkles}>AI with boundaries</Eyebrow><h2 className="mt-5 text-4xl font-semibold text-white">Intelligence can explain the work without owning it.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-canopy-secondary">Canopy AI summarizes paths, retrieves memory, and cites the creative history it used. It does not rewrite authoritative versions or become the source of truth.</p></div><CopilotPreview /></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><Eyebrow icon={Icons.Braces}>For developers</Eyebrow><h2 className="mt-5 text-4xl font-semibold text-white">Creative context for tools and agents.</h2><p className="mt-5 text-lg leading-8 text-canopy-secondary">Use the Canopy API and MCP interface to inspect authorized creative history without bypassing Core.</p><SecondaryLink to="/developers" className="mt-7">Explore developer platform</SecondaryLink></div><DeveloperFlow /></div></section>
    <FinalCta />
  </PageMeta>;
}

export function FeaturesPage() { return <PageMeta title="Features | Canopy" description="Explore Canopy creative versioning, lineage, semantic diff, memory, provenance, and Copilot."><PublicPageHero eyebrow="Platform features" title="A foundation for creative work that needs to last." body="Canopy turns each meaningful change into a reusable creative record." /><section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="space-y-16">{stories.map((story, i) => <FeatureStory key={story[0]} story={story} flip={i % 2} />)}</div></section></PageMeta>; }

export function HowItWorksPage() {
  const steps = [['01', 'Create a project', 'Give work a purpose and home.'], ['02', 'Capture versions', 'Record import, edit, generate, and merge actions.'], ['03', 'Branch directions', 'Keep alternatives without losing a shared origin.'], ['04', 'Compare meaning', 'Use semantic diff to see what shifted.'], ['05', 'Preserve memory', 'Save decisions beyond the graph.'], ['06', 'Continue with context', 'Return to any version with evidence intact.']];
  return <PageMeta title="How Canopy Works | Canopy" description="Follow the Canopy creative workflow from project through continuation."><PublicPageHero eyebrow="How Canopy works" title="A continuous record of creative decisions." body="Capture the work, preserve the context, and make the next decision with both." /><section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><CreativeLineagePreview compact /><ol className="mt-16 grid gap-px border border-canopy-border bg-canopy-border md:grid-cols-2 lg:grid-cols-3">{steps.map(([number, title, body]) => <li key={number} className="bg-canopy-bg p-6"><span className="font-mono text-xs text-canopy-green">{number}</span><h2 className="mt-6 text-xl font-semibold text-white">{title}</h2><p className="mt-3 text-sm leading-6 text-canopy-secondary">{body}</p></li>)}</ol></section></PageMeta>;
}

export function UseCasesPage() {
  const cases = [['Independent creators', 'Return to the reason a direction changed after weeks away.'], ['Creative teams', 'Review work with its decisions, branches, and provenance intact.'], ['AI-assisted workflows', 'Separate model assistance from human choices.'], ['Agencies', 'Preserve handoff context through long-running client work.'], ['Product and design', 'Make exploration traceable without flattening it into tickets.'], ['Asset archives', 'Keep durable creative history alongside assets.']];
  return <PageMeta title="Use Cases | Canopy" description="Canopy use cases for creators, teams, agencies, and AI-assisted work."><PublicPageHero eyebrow="Use cases" title="For work that changes hands, tools, and directions." body="Canopy gives different creative practices a common history without forcing them into the same process." /><section className="mx-auto grid max-w-7xl gap-px px-5 pb-24 sm:grid-cols-2 lg:grid-cols-3 lg:px-8">{cases.map(([title, body], index) => <article key={title} className="border border-canopy-border bg-canopy-surface p-6"><span className="font-mono text-xs text-canopy-green">0{index + 1}</span><h2 className="mt-8 text-xl font-semibold text-white">{title}</h2><p className="mt-3 text-sm leading-6 text-canopy-secondary">{body}</p></article>)}</section></PageMeta>;
}

export function DevelopersPage() { return <PageMeta title="Developers | Canopy" description="Build with the Canopy REST API, domain contracts, and MCP interface."><PublicPageHero eyebrow="Developer platform" title="Build tools that understand creative history." body="The Canopy REST API and MCP server expose authorized project, version, lineage, diff, and memory context through the same Core boundary." /><section className="mx-auto grid max-w-7xl gap-10 px-5 pb-24 lg:grid-cols-2 lg:px-8"><DeveloperFlow /><div className="border border-canopy-border bg-canopy-surface p-6"><p className="font-mono text-xs text-canopy-green">GET /v1/projects/:projectId/lineage</p><pre className="mt-6 overflow-x-auto text-sm leading-7 text-canopy-secondary">{'{\n  "versions": ["..."],\n  "edges": ["..."],\n  "branch_points": ["..."],\n  "tips": ["..."]\n}'}</pre><p className="mt-6 text-sm leading-6 text-canopy-secondary">The displayed route and fields mirror the committed API contract. Authentication and ownership remain enforced by the API.</p><PrimaryLink to="/docs" className="mt-7">Read documentation <Icons.ArrowRight className={iconSize.ui} /></PrimaryLink></div></section></PageMeta>; }

export function DocumentationPage() {
  const docs = [['Getting started', 'Repository setup and environment', '/docs'], ['REST API', 'OpenAPI 3.1 reference and typed errors', '/developers'], ['MCP', 'Read tools for authorized AI-agent access', '/developers'], ['Creative versions', 'Version and lineage contracts', '/how-it-works'], ['Semantic diff', 'Declared, path, and observed evidence', '/features'], ['Architecture', 'Core, intelligence, and PostgreSQL boundaries', '/how-it-works']];
  return <PageMeta title="Documentation | Canopy" description="Start with Canopy documentation, API, MCP, and creative workflow references."><PublicPageHero eyebrow="Documentation" title="The reference point for Canopy." body="Start with the product model, then move through API, MCP, creative versions, and the architecture that keeps history authoritative." /><section className="mx-auto grid max-w-7xl gap-3 px-5 pb-24 sm:grid-cols-2 lg:grid-cols-3 lg:px-8">{docs.map(([title, body, to]) => <Link to={to} key={title} className="group border border-canopy-border bg-canopy-surface p-5 transition hover:border-canopy-green"><Icons.BookOpen className="h-5 w-5 text-canopy-green" /><h2 className="mt-7 text-lg font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-canopy-secondary">{body}</p><span className="mt-5 inline-flex items-center gap-2 text-sm text-canopy-green">Explore <Icons.ArrowRight className={iconSize.ui} /></span></Link>)}</section></PageMeta>;
}

export function PricingPage() { return <PageMeta title="Pricing | Canopy" description="Canopy pricing is currently prototype and coming soon."><PublicPageHero eyebrow="Pricing" title="A product model is still taking shape." body="Canopy is a prototype. Pricing, plans, and payment flows are not available yet, so this page does not invent them." /><section className="mx-auto max-w-3xl px-5 pb-24 lg:px-8"><div className="border border-canopy-green/40 bg-canopy-surface p-8"><Eyebrow icon={Icons.CircleHelp}>Prototype / coming soon</Eyebrow><h2 className="mt-5 text-3xl font-semibold text-white">Build with the public foundation today.</h2><p className="mt-4 max-w-xl text-base leading-7 text-canopy-secondary">Explore the product model, documentation, and deterministic demo workflow. Commercial plans will only appear here when they are real.</p><div className="mt-7 flex flex-wrap gap-3"><PrimaryLink to="/signup">Create an account <Icons.ArrowRight className={iconSize.ui} /></PrimaryLink><SecondaryLink to="/contact">Contact support</SecondaryLink></div></div></section></PageMeta>; }

export function ContactPage() { return <PageMeta title="Contact | Canopy" description="Find Canopy support and documentation."><PublicPageHero eyebrow="Contact" title="Start with the right context." body="There is no server-backed contact form in the prototype, so Canopy opens your mail client instead of pretending a message was submitted." /><section className="mx-auto grid max-w-5xl gap-4 px-5 pb-24 md:grid-cols-3 lg:px-8"><ContactCard icon={Icons.MessageSquareText} title="Support" body="Questions about using the prototype or local setup." href="mailto:support@canopy.local" label="Email support" /><ContactCard icon={Icons.BookOpen} title="Documentation" body="Product, API, MCP, and architecture references." to="/docs" label="Open docs" /><ContactCard icon={Icons.Code2} title="Developers" body="REST API and MCP implementation details." to="/developers" label="Developer platform" /></section></PageMeta>; }

export function AndroidDownloadPage() { return <PageMeta title="Canopy for Android | Canopy" description="Run the Canopy React Native Android public experience with Expo."><PublicPageHero eyebrow="Android" title="Canopy, designed for a smaller canvas." body="The React Native public experience keeps the same product language while using mobile navigation and vertical storytelling." /><section className="mx-auto max-w-3xl px-5 pb-24 lg:px-8"><div className="border border-canopy-border bg-canopy-surface p-7"><h2 className="text-xl font-semibold text-white">React Native and Expo</h2><ol className="mt-6 space-y-4 border-l border-canopy-border pl-6 text-sm leading-6 text-canopy-secondary"><li><code className="text-canopy-green">pnpm install</code></li><li><code className="text-canopy-green">pnpm --filter @canopy/android start</code></li><li><code className="text-canopy-green">pnpm --filter @canopy/android android</code></li></ol></div></section></PageMeta>; }

export function NotFoundPage() { return <PageMeta title="Page not found | Canopy" description="This Canopy route does not exist."><section className="mx-auto max-w-3xl px-5 py-32 lg:px-8"><Eyebrow icon={Icons.CircleHelp}>404</Eyebrow><h1 className="mt-5 text-5xl font-semibold text-white">This route has no history yet.</h1><p className="mt-5 text-lg text-canopy-secondary">Return to the public foundation or open the workspace.</p><PrimaryLink to="/" className="mt-8">Back to home <Icons.ArrowRight className={iconSize.ui} /></PrimaryLink></section></PageMeta>; }

function ProblemSection() { return <section className="border-y border-canopy-border bg-canopy-surface/50"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-24 lg:grid-cols-[0.75fr_1.25fr] lg:px-8"><div><Eyebrow icon={Icons.Network}>Why Canopy</Eyebrow><h2 className="mt-5 text-4xl font-semibold leading-tight text-white">Creative work now crosses people, tools, versions, and AI systems.</h2></div><p className="self-end text-lg leading-8 text-canopy-secondary">Important decisions disappear in the handoff. Canopy preserves the context around the work so a file can become a usable creative record again.</p></div></section>; }
function FeatureStory({ story: [title, headline, body, Icon, visual], flip }) { return <article className="grid items-center gap-10 border-t border-canopy-border pt-16 lg:grid-cols-2"><div className={flip ? 'lg:order-2' : ''}><Eyebrow icon={Icon}>{title}</Eyebrow><h2 className="mt-5 text-3xl font-semibold leading-tight text-white">{headline}</h2><p className="mt-5 max-w-lg text-base leading-7 text-canopy-secondary">{body}</p><Link to="/features" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-canopy-green hover:text-white">Explore {title}<Icons.ArrowRight className={iconSize.ui} /></Link></div><div className={flip ? 'lg:order-1' : ''}>{visual === 'lineage' ? <CreativeLineagePreview compact /> : visual === 'diff' ? <DiffPreview /> : <CopilotPreview />}</div></article>; }
function PublicPageHero({ eyebrow, title, body }) { return <section className="mx-auto max-w-7xl px-5 pb-16 pt-20 lg:px-8 lg:pb-20 lg:pt-28"><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[1.05] text-white sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-canopy-secondary">{body}</p></section>; }
function SectionHeading({ eyebrow, title, body }) { return <div className="max-w-2xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-5 text-4xl font-semibold text-white">{title}</h2><p className="mt-5 text-lg leading-8 text-canopy-secondary">{body}</p></div>; }
function Eyebrow({ icon: Icon, children }) { return <span className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-canopy-green">{Icon ? <Icon className={iconSize.ui} /> : null}{children}</span>; }
function PrimaryLink({ to, children, className = '' }) { return <Link to={to} className={'inline-flex items-center gap-2 rounded-md bg-[#43D391] px-4 py-3 text-sm font-semibold text-[#06251A] transition hover:bg-[#4ee0a0] ' + className}>{children}</Link>; }
function SecondaryLink({ to, children, className = '' }) { return <Link to={to} className={'inline-flex items-center gap-2 rounded-md border border-canopy-border px-4 py-3 text-sm font-semibold text-white transition hover:border-canopy-green hover:bg-canopy-surface ' + className}>{children}</Link>; }
function ContactCard({ icon: Icon, title, body, href, to, label }) { const content = <><Icon className="h-6 w-6 text-canopy-green" /><h2 className="mt-8 text-xl font-semibold text-white">{title}</h2><p className="mt-3 text-sm leading-6 text-canopy-secondary">{body}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-canopy-green">{label}<Icons.ArrowRight className={iconSize.ui} /></span></>; return href ? <a href={href} className="border border-canopy-border bg-canopy-surface p-6 transition hover:border-canopy-green">{content}</a> : <Link to={to} className="border border-canopy-border bg-canopy-surface p-6 transition hover:border-canopy-green">{content}</Link>; }
function FinalCta() { return <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="border border-canopy-border bg-canopy-surface px-6 py-14 text-center sm:px-12"><Eyebrow icon={Icons.Sparkles}>Keep the story</Eyebrow><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold text-white">Keep the work. Keep the decisions. Keep the context.</h2><div className="mt-8 flex justify-center gap-3"><PrimaryLink to="/signup">Get started <Icons.ArrowRight className={iconSize.ui} /></PrimaryLink><SecondaryLink to="/docs">Explore documentation</SecondaryLink></div></div></section>; }
function PageMeta({ title, description, children }) { useEffect(() => { document.title = title; const meta = document.querySelector('meta[name="description"]'); if (meta) meta.setAttribute('content', description); }, [title, description]); return <>{children}</>; }
